spring.application.name=life-os
server.port=9091
spring.datasource.url=jdbc:postgresql://localhost:5432/life_os_db
spring.datasource.username=postgres
spring.datasource.password=Root@123
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
app.jwt.secret=9a4f2c8d7b3a1e5f8c6b9a4f2c8d7b3a1e5f8c6b9a4f2c8d7b3a1e5f8c6b9a4f
app.jwt.expiration-ms=86400000
