spring.application.name=life-os
server.port=9091
spring.datasource.url=jdbc:postgresql://localhost:5432/life_os_db
spring.datasource.username=postgres
spring.datasource.password=Root@123
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
app.jwt.secret=9a4f2c8d7b3a1e5f8c6b9a4f2c8d7b3a1e5f8c6b9a4f2c8d7b3a1e5f8c6b9a4f
app.jwt.expiration-ms=86400000

app.oauth2.google.client-id=YOUR_GOOGLE_CLIENT_ID
app.oauth2.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
app.oauth2.google.redirect-uri=YOUR_GOOGLE_REDIRECT_URI

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_GMAIL_ADDRESS
spring.mail.password=YOUR_GMAIL_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.ai.openai.api-key=YOUR_OPENAI_API_KEY
spring.ai.openai.chat.options.model=gpt-4o-mini

management.endpoints.web.exposure.include=health,info,metrics,env
management.endpoint.health.show-details=always

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.group-id=lifeos-group

# Tolerance settings for offline local development
spring.kafka.listener.auto-startup=false
spring.kafka.admin.fail-fast=false
